agentLink + websocket testing (#65)
* Agenteract websocket interface (AgentClient): Implemented direct websocket connectivity with interaction primitives. 
Improves interaction speed by skipping process execution. Improves e2e testing by up to 75%.
* agentLink: Similar to deep link, but can be subscribed to via AgentDebugBridge. This resolves issues around duplicate activity launching. 
DeepLinking is still used for device pairing
* Lifecycle Utils: Implemented command line and websocket support for building and launching apps. Supports PTY based launching in Expo Go and Flutter.

diff --git a/.github/workflows/e2e-vite.yml b/.github/workflows/e2e-vite.yml
--- a/.github/workflows/e2e-vite.yml
+++ b/.github/workflows/e2e-vite.yml
@@ -73,4 +73,5 @@ jobs:
 
       - name: Cleanup
         if: always()
-        run: pnpm verdaccio:stop
+        # Mask 143 exit code, we aren't testing verdaccio
+        run: pnpm verdaccio:stop || true
